/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_jcyh_peephole_utils_PatchUtil */

#ifndef _Included_cn_jcyh_peephole_utils_PatchUtil
#define _Included_cn_jcyh_peephole_utils_PatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_jcyh_peephole_utils_PatchUtil
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_jcyh_peephole_utils_PatchUtil_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
